// this code is autogenerated, do not check it into to your code repository

// ref gh_events_analysis/data_processing_test.livemd#cell:otgktjpqyhsc3u7wwhkemax5ntkhm5oc:3
pub fn example_fun(value1: f64, value2: f64) bool {
  return value1 > value2;
}
